apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    args:
    - /bin/bash
    - -c
    - redis-server /usr/local/etc/redis/redis.conf
    env:
      - name: REDIS_LITRAL_DATABASE_EXAMPLE
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: database
      - name: REDIS_CONFIG_EXAMPLE
        valueFrom:
          configMapKeyRef:
            name: redis-config
            key: redis.conf
    volumeMounts:
    - mountPath: /usr/local/etc/redis
      name: config
    - mountPath: /data
      name: data
  volumes:
    - name: config
      configMap:
        name: redis-config
        items: 
        - key: redis.conf
          path: redis.conf
    - name: data
      emptyDir: {}
