apiVersion: apps/v1
kind: Deployment
metadata:				#rc
  name: nginx-deployment
spec:					#rc
  template:
    metadata:        #dictionary   	#pod
      name: nginx-pod
      labels:
        type: front-end
    spec:				#pod
      containers:    # list/array
      - name: nginx
        image: nginx
  replicas: 2
  selector:
    matchLabels:
      type: front-end
