apiVersion: v1 			# String
kind: Pod			# String
metadata:			# Dictionary
  name: mysql
  labels:
    db: mysql
spec:
  containers:			# List/Array
    - name: mysql-container	# 1st item in an array
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password
      volumeMounts:
        - name: credentials-volume
          mountPath: /tmp/credentials
  volumes:
    - name: credentials-volume
      secret:
        secretName: db-user-pass

